# Based on https://habrahabr.ru/post/329264/
# Additional GCC / clang versions:
#   - https://docs.travis-ci.com/user/languages/cpp/
#   - https://gist.github.com/nabijaczleweli/e53219d037c4ccb34f3c
# Useful samples:
#   - https://github.com/catchorg/Catch2/blob/master/.travis.yml
#   - https://github.com/pinam45/dynamic_bitset/blob/master/.travis.yml
#

dist: xenial

language: cpp

git:
  #depth: 1
  submodules: true

cache:
    apt: true

addons:
    apt:
        sources: &apt_sources
            - ubuntu-toolchain-r-test
        #packages:
        #    - g++-5

    homebrew: &homebrew
        packages:
            - python
            - ffmpeg
            - meson

# Is there any way to avoid duplication for combination of BUILD_CONFIGURATION and COMPILER?
# in case, when non-default compiler is used?
jobs:
    include:
        # GCC 8 / Debug
        - os: linux
          addons: &gcc8
            apt:
                sources: *apt_sources
                packages:
                    - g++-8
          compiler: gcc
          env:
            - MATRIX_EVAL="BUILD_TYPE=Debug && CC=gcc-8 && CXX=g++-8"

        # GCC 8 / Release
        - os: linux
          addons: *gcc8
          compiler: gcc
          env:
            - MATRIX_EVAL="BUILD_TYPE=Release && CC=gcc-8 && CXX=g++-8"

        # GCC 5 / Debug
        - os: linux
          addons: &gcc5
            apt:
              sources: *apt_sources
              packages:
                - g++-5
          compiler: gcc
          env:
            - MATRIX_EVAL="BUILD_TYPE=Debug && CC=gcc-5 && CXX=g++-5"

        # GCC 5 / Release
        - os: linux
          addons: *gcc5
          compiler: gcc
          env:
            - MATRIX_EVAL="BUILD_TYPE=Release && CC=gcc-5 && CXX=g++-5"

        - os: linux
          dist: bionic
          compiler: gcc
          env:
            - MATRIX_EVAL="BUILD_TYPE=Release"

        - os: osx
          osx_image: xcode11.3
          compiler: clang
          env:
            - MATRIX_EVAL="BUILD_TYPE=Debug"

        - os: osx
          osx_image: xcode11.3
          compiler: clang
          env:
            - MATRIX_EVAL="BUILD_TYPE=Release"

#    exclude:
        # exclude some elements from build matrix:
#        - os:       osx
#          compiler: gcc

        #- compiler: gcc
        #  env: BUILD_CONFIGURATION=Debug

        #- compiler: gcc
        #  env: BUILD_CONFIGURATION=Release

#before_install:
#    - eval "${MATRIX_EVAL}"

install:
    # setup env:
    - source ci/travis/install-$TRAVIS_OS_NAME.sh

script:
    - eval "${MATRIX_EVAL}"
    # build and test project with cmake:
    - mkdir build
    - cd build
    #- cmake .. -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION -DTARGET_CPU=$TARGET_CPU
    - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE
    - cmake --build .
    - ctest --output-on-failure
    - cd ..
    # build and test project with meson:
    - mkdir builddir
    - cd builddir
    - meson setup ..
    - meson configure --buildtype $BUILD_TYPE
    - meson compile
    - meson test
    - cd ..

#deploy:
#    # push tagged-commits to GitHub Releases:
#    provider:     releases
#    file:         <package-file>
#    skip_cleanup: true
#    overwrite:    true
#
#    api_key:
#        secure:   <encrypted-github-token>
#
#    on:
#        tags:     true

