# Based on https://habrahabr.ru/post/329264/
# Additional GCC / clang versions:
#   - https://docs.travis-ci.com/user/languages/cpp/

dist: xenial
sudo: required

language: cpp

os:
    - linux
    - osx

compiler:
    - gcc
    - clang

env:
    - BUILD_CONFIGURATION=Debug
    - BUILD_CONFIGURATION=Release

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-xenial-7
        packages:
            - gcc-8
            - clang-7

matrix:
    include:
        - compiler: gcc
          env:
            - MATRIX_EVAL="BUILD_CONFIGURATION=Debug && CC=gcc-8 && CXX=g++-8"

        - compiler: gcc
          env:
            - MATRIX_EVAL="BUILD_CONFIGURATION=Release && CC=gcc-8 && CXX=g++-8"

        - compiler: gcc
          env:
            - MATRIX_EVAL="BUILD_CONFIGURATION=Debug && CC=gcc-5 && CXX=g++-5"

        - compiler: gcc
          env:
            - MATRIX_EVAL="BUILD_CONFIGURATION=Release && CC=gcc-5 && CXX=g++-5"

        - compiler: clang
          os: linux
          env:
            - MATRIX_EVAL="CC=clang-7 && CXX=clang++-7"

    exclude:
        # exclude some elements from build matrix:
        - os:       osx
          compiler: gcc

        - compiler: gcc
          env: BUILD_CONFIGURATION=Debug

        - compiler: gcc
          env: BUILD_CONFIGURATION=Release

#before_install:
#    - eval "${MATRIX_EVAL}"

install:
    # setup env:
    - source ci/travis/install-$TRAVIS_OS_NAME.sh
    - eval "${MATRIX_EVAL}"

script:
    # build and test project:
    - mkdir build
    - cd build
    #- cmake .. -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION -DTARGET_CPU=$TARGET_CPU
    - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION
    - cmake --build .
    #- ctest --output-on-failure

#deploy:
#    # push tagged-commits to GitHub Releases:
#    provider:     releases
#    file:         <package-file>
#    skip_cleanup: true
#    overwrite:    true
#
#    api_key:
#        secure:   <encrypted-github-token>
#
#    on:
#        tags:     true

